name: Translate GitBook

on:
  push:
    branches: ["main]
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai==0.28.0  # Specify the latest compatible version

    - name: Translate GitBook content
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python translate_gitbook.py

    - name: Commit changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}  # Use the PAT stored in the repository secrets
      run: |
        git config --global user.name 'jegamboafuentes'
        git config --global user.email 'jegamboafuentes@gmail.com'
        git remote set-url origin https://jegamboafuentes:${{ secrets.GH_PAT }}@github.com/MIT-Bitcoin-2024/demo-gitbook.git
        git add .
        git commit -m 'Translated GitBook content'
        git push https://jegamboafuentes:${{ secrets.GH_PAT }}@github.com/MIT-Bitcoin-2024/demo-gitbook.git HEAD:main
